services:
  OneFrame:
    restart: always
    image: smartpayco/smartcloud:latest
    ports:
      - "9999:9999"
  # Redis:
  #   restart: always
  #   image: redis:6.2.0
  #   ports:
  #     - "6379:6379"
  #   environment:
  #     - DEBUG=false