services:
  Smartcloud:
    restart: always
    image: smartpayco/smartcloud:latest
    ports:
      - "9999:9999"
  Redis:
    restart: always
    image: redis:latest
    ports:
     - "6379:6379"
    environment:
     - DEBUG=false